/**
 * Imposter API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IPlayer } from './iPlayer';
import { IRound } from './iRound';
import { IScoreboardRow } from './iScoreboardRow';


export interface IGame { 
    id?: string;
    easyCode?: string;
    host?: IPlayer;
    players?: Array<IPlayer>;
    currentRound?: IRound;
    previousRounds?: Array<IRound>;
    readonly scores?: Array<IScoreboardRow>;
    readonly state?: string;
    readonly canLeaveWithoutRoundCancellation?: boolean;
}
