/**
 * Imposter API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IRoundParticipant } from './iRoundParticipant';


export interface IRound { 
    readonly id?: string;
    readonly word?: string;
    impostersGuess?: string;
    readonly isGuessCorrect?: boolean;
    readonly allOptions?: Array<string>;
    readonly participants?: Array<IRoundParticipant>;
    imposter?: IRoundParticipant;
    readonly allAnswered?: boolean;
    readonly allAccused?: boolean;
    isComplete?: boolean;
}
